<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>98aca127-861c-4f33-ad04-6b5c96d38efb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Base\Session\**" />
    <Content Remove="Base\Session\**" />
    <EmbeddedResource Remove="Base\Session\**" />
    <None Remove="Base\Session\**" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="MudBlazor" Version="8.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
	<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logs\" />
  </ItemGroup>

</Project>
