
\set ON_ERROR_STOP on

-- Schemas (uncomment if needed)
CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS base;
CREATE SCHEMA IF NOT EXISTS cntrl;

CREATE SEQUENCE IF NOT EXISTS cntrl.temp_id
    START WITH 10000
    INCREMENT BY 1
    OWNED BY NONE;

CREATE TABLE cntrl.loginoption (
    urlsuffix TEXT PRIMARY KEY NOT NULL,
	isdefault BOOLEAN NOT NULL DEFAULT FALSE,
    orgnr INTEGER NOT NULL,
	orgnrs TEXT NOT NULL,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
    langcode VARCHAR(4) NOT NULL,
    langlabelvariant INTEGER NOT NULL,
	langcodes TEXT,
	successaction INTEGER NOT NULL DEFAULT 0
);

COMMENT ON TABLE cntrl.loginoption IS 'Used by the FrontendLogin screen to configure options and workflows (will be validated in the Backend';
COMMENT ON COLUMN cntrl.loginoption.orgnr IS 'Default org nr for this option';
COMMENT ON COLUMN cntrl.loginoption.langcode IS 'Default language code for this option';
COMMENT ON COLUMN cntrl.loginoption.langlabelvariant IS 'Default language code variant for this option';
COMMENT ON COLUMN cntrl.loginoption.urlsuffix IS 'End part of the login URL - returns the options to the browser';
COMMENT ON COLUMN cntrl.loginoption.successaction IS '0 == navigate to FrontendServer, 1 == stop and display tokens (for api)';

CREATE TABLE cntrl.tokenrefresh (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
	token UUID NOT NULL,
	created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	createdbyip TEXT NOT NULL,
    username TEXT NOT NULL,
    sessionkey TEXT NOT NULL,
    orgnr INTEGER,
	expires TIMESTAMPTZ NOT NULL,
	revoked TIMESTAMPTZ,
	revokedby TEXT
);

COMMENT ON TABLE cntrl.tokenrefresh IS 'Persist client refresh tokens, note JWTokens are not persisted in the DB (they are in memory)';

CREATE TABLE base.org (
    nr INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    descr TEXT NOT NULL,
    encoded TEXT,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
    langcode VARCHAR(4) NOT NULL,
    langlabelvariant INTEGER NOT NULL,
	icon TEXT,
	apikey TEXT, 
	mfa INTEGER NOT NULL DEFAULT 0,
	isremembermeenabled BOOLEAN DEFAULT FALSE,
	ismasqueradeenabled BOOLEAN DEFAULT FALSE,
	ispasswordresetenabled BOOLEAN DEFAULT FALSE,
	issignupenabled BOOLEAN DEFAULT FALSE,
	isemailrequired BOOLEAN DEFAULT FALSE,
	isemailverified BOOLEAN DEFAULT FALSE,
	isemailhtml BOOLEAN DEFAULT TRUE
);

COMMENT ON TABLE base.org IS 'Organisation entity (system can have mulitple Organisations';
COMMENT ON COLUMN base.org.apikey IS 'Secrete key to allow api logins';
COMMENT ON COLUMN base.org.mfa IS '0 = inactive, 1 = optional per day, 2 = required per day, 3 = required each login';
COMMENT ON COLUMN base.org.ispasswordresetenabled IS 'Users can request a password reset via email';
COMMENT ON COLUMN base.org.issignupenabled IS 'Self registration is enabled, ie users can sign up';
COMMENT ON COLUMN base.org.isemailrequired IS 'Users must have an email address';
COMMENT ON COLUMN base.org.isemailverified IS 'User''s emails must be verified before they can login for the first time';
COMMENT ON COLUMN base.org.isemailhtml IS 'Are emails send in HTML';

CREATE TABLE base.zzz (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    xxx VARCHAR(40) NOT NULL UNIQUE,
    yyy VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	isemailverified BOOLEAN DEFAULT FALSE,
	orgnrdefault INTEGER NOT NULL,
    langcode VARCHAR(4) NOT NULL,
    attempts INTEGER DEFAULT 0,
	attemptslockout TIMESTAMPTZ,
    lastlogin TIMESTAMPTZ,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
	ismfarequired BOOLEAN DEFAULT FALSE,
	ismfaenabled BOOLEAN DEFAULT FALSE,
	mfasecret VARCHAR(100),	
	updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
);

COMMENT ON TABLE base.zzz IS 'User authentication (see base.useracc for authorisation)';
COMMENT ON COLUMN base.zzz.xxx IS 'Username';
COMMENT ON COLUMN base.zzz.yyy IS 'User password';
COMMENT ON COLUMN base.zzz.attempts IS 'Current number of consecutive login fails';
COMMENT ON COLUMN base.zzz.attemptslockout IS 'The start timestamp of a login lockout';
COMMENT ON COLUMN base.zzz.isemailverified IS 'User''s email address has been verified';
COMMENT ON COLUMN base.zzz.orgnrdefault IS 'Used for determining the user''s org settings, eg password reset';
COMMENT ON COLUMN base.zzz.ismfarequired IS 'Depends on the org, if org = optional then mfa is used if true';

CREATE TABLE base.useracc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    zzzid BIGINT NOT NULL,
    orgnr INTEGER NOT NULL,
    lastlogin TIMESTAMPTZ,
    classification INTEGER DEFAULT 0,
    isadmin BOOLEAN NOT NULL DEFAULT FALSE,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
	updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    FOREIGN KEY (zzzid) REFERENCES base.zzz(id),
    FOREIGN KEY (orgnr) REFERENCES base.org(nr)
);

CREATE TABLE base.role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    orgnr INTEGER NOT NULL,
    code VARCHAR(100) NOT NULL,
    descr TEXT,
    encoded TEXT,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    UNIQUE (orgnr, code),
    FOREIGN KEY (orgnr) REFERENCES base.org(nr)
);

CREATE TABLE base.rolepermission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    roleid BIGINT NOT NULL,
    permissionnr INTEGER NOT NULL,
    crud VARCHAR(10) NOT NULL,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    UNIQUE (roleid, permissionnr),
    FOREIGN KEY (roleid) REFERENCES base.role(id)
);

CREATE TABLE base.useraccrole (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    useraccid BIGINT NOT NULL,
    roleid BIGINT NOT NULL,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    UNIQUE (useraccid, roleid),
    FOREIGN KEY (useraccid) REFERENCES base.useracc(id),
    FOREIGN KEY (roleid) REFERENCES base.role(id)
);

CREATE TABLE base.langcode (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(4) NOT NULL,
    descr TEXT NOT NULL,
    encoded TEXT,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    isactive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE base.langkey (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack TEXT,
    code VARCHAR(100) NOT NULL UNIQUE,
    descr TEXT,
    encoded TEXT,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE base.langlabel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    langkeyid BIGINT NOT NULL,
    langcode VARCHAR(4) NOT NULL,
    variant INTEGER,
    code TEXT NOT NULL,
    tooltip TEXT,
    encoded TEXT,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    UNIQUE (langkeyid, langcode, variant),
    FOREIGN KEY (langkeyid) REFERENCES base.langkey(id)
);

CREATE TABLE base.audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orgnr INTEGER NOT NULL,
    source INTEGER NOT NULL,
    entitytypeid INTEGER NOT NULL,
    entityid BIGINT,
    useraccid BIGINT NOT NULL,
	masqueradeid BIGINT,
    created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    crud VARCHAR(10),
    details TEXT
);

COMMENT ON TABLE base.audit IS 'Log of all CRUD transations ';
COMMENT ON COLUMN base.audit.source IS 'Client source, eg web, mobile, api';
COMMENT ON COLUMN base.audit.entitytypeid IS 'The entity defined in GC EntityTypes, eg Role, Org';
COMMENT ON COLUMN base.audit.entityid IS 'The primary key for the entity in question';
COMMENT ON COLUMN base.audit.useraccid IS 'User Id';
COMMENT ON COLUMN base.audit.masqueradeid IS 'User Id of account that is using masquerade';
COMMENT ON COLUMN base.audit.crud IS 'CRUD action';

--Delete me?
CREATE TABLE base.template (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nr INTEGER NOT NULL,
	orgnr INTEGER NOT NULL,
    code TEXT NOT NULL,
    langcode VARCHAR(4) NOT NULL,
	UNIQUE (nr, orgnr, langcode)
);