
\set ON_ERROR_STOP on

-- Schemas (uncomment if needed)
CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS base;
CREATE SCHEMA IF NOT EXISTS cntrl;

CREATE SEQUENCE IF NOT EXISTS cntrl.temp_id
    START WITH 10000
    INCREMENT BY 1
    OWNED BY NONE;

CREATE OR REPLACE FUNCTION immutable_unaccent(text)
	RETURNS text
	LANGUAGE sql
	IMMUTABLE
	AS $$
		SELECT public.unaccent($1);
	$$;

CREATE TABLE cntrl.loginOption (
    urlSuffix TEXT PRIMARY KEY NOT NULL,
	isDefault BOOLEAN NOT NULL DEFAULT FALSE,
    orgNr INTEGER NOT NULL,
	orgNrs TEXT NOT NULL, --DELETE ME
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
    langCode VARCHAR(4) NOT NULL,
    langLabelVariant INTEGER NOT NULL,
	langCodes TEXT,
	isMasqueradeEnabled BOOLEAN DEFAULT FALSE,
	successAction INTEGER NOT NULL DEFAULT 0
);

COMMENT ON TABLE cntrl.loginOption IS 'Used by the FrontendLogin screen to configure options and workflows (will be validated in the Backend';
COMMENT ON COLUMN cntrl.loginOption.orgNr IS 'Default org nr for this option';
COMMENT ON COLUMN cntrl.loginOption.langCode IS 'Default language code for this option';
COMMENT ON COLUMN cntrl.loginOption.langLabelVariant IS 'Default language code variant for this option';
COMMENT ON COLUMN cntrl.loginOption.urlsuffix IS 'End part of the login URL - returns the options to the browser';
COMMENT ON COLUMN cntrl.loginOption.successAction IS '0 == navigate to FrontendServer, 1 == stop and display tokens (for api)';

CREATE TABLE cntrl.tokenRefresh (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
	token UUID NOT NULL,
	created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	createdByIp TEXT NOT NULL,
    userName TEXT NOT NULL,
    sessionKey TEXT NOT NULL,
    orgNr INTEGER,
	expires TIMESTAMPTZ NOT NULL,
	revoked TIMESTAMPTZ,
	revokedBy TEXT
);

COMMENT ON TABLE cntrl.tokenRefresh IS 'Persist client refresh tokens, note JWTokens are not persisted in the DB (they are in memory)';

CREATE TABLE base.org (
    nr INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    descr TEXT NOT NULL,
    encoded TEXT,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
    langCode VARCHAR(4) NOT NULL,
    langLabelVariant INTEGER NOT NULL,
	icon TEXT,
	apiKey TEXT, 
	mfa INTEGER NOT NULL DEFAULT 0,
	isRememberMeEnabled BOOLEAN DEFAULT FALSE,
	isMasqueradeEnabled BOOLEAN DEFAULT FALSE,
	isPasswordResetEnabled BOOLEAN DEFAULT FALSE,
	isSignUpEnabled BOOLEAN DEFAULT FALSE,
	isEmailRequired BOOLEAN DEFAULT FALSE,
	isEmailVerified BOOLEAN DEFAULT FALSE,
	isEmailHtml BOOLEAN DEFAULT TRUE
);

COMMENT ON TABLE base.org IS 'Organisation entity (system can have mulitple Organisations';
COMMENT ON COLUMN base.org.apiKey IS 'Secrete key to allow api logins';
COMMENT ON COLUMN base.org.mfa IS '0 = inactive, 1 = optional per day, 2 = required per day, 3 = required each login';
COMMENT ON COLUMN base.org.isPasswordResetEnabled IS 'Users can request a password reset via email';
COMMENT ON COLUMN base.org.isSignUpEnabled IS 'Self registration is enabled, ie users can sign up';
COMMENT ON COLUMN base.org.isEmailRequired IS 'Users must have an email address';
COMMENT ON COLUMN base.org.isEmailVerified IS 'User''s emails must be verified before they can login for the first time';
COMMENT ON COLUMN base.org.isEmailHtml IS 'Are emails send in HTML';

CREATE TABLE base.orgEntity (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    orgNr INTEGER NOT NULL,
	refOrgNr INTEGER NOT NULL,
	entityTypeNr INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (orgNr) REFERENCES base.org(nr),
	FOREIGN KEY (refOrgNr) REFERENCES base.org(nr)
);
COMMENT ON TABLE base.orgEntity IS 'Controls what entity types are read only in a org';
COMMENT ON COLUMN base.orgEntity.refOrgNr IS 'Reference org nr that ''owns'' the entity';
COMMENT ON COLUMN base.orgEntity.entityTypeNr IS 'The entity defined in GC EntityTypes, eg Role, Org';

CREATE TABLE base.orgGroup (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
	code VARCHAR(100) NOT NULL,
    orgNr INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (orgNr) REFERENCES base.org(nr)
);
COMMENT ON TABLE base.orgGroup IS 'A logical group of orgs, ie users can have accounts for orgs in the group';
COMMENT ON COLUMN base.orgGroup.code IS 'Group name';

CREATE TABLE base.zzz (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    xxx VARCHAR(40) NOT NULL UNIQUE,
    yyy TEXT NOT NULL,
	encoded TEXT,
	email VARCHAR(100),
	isEmailVerified BOOLEAN DEFAULT FALSE,
	orgNrDefault INTEGER NOT NULL,
    langCode VARCHAR(4) NOT NULL,
    attempts INTEGER DEFAULT 0,
	attemptsLockOut TIMESTAMPTZ,
    lastLogin TIMESTAMPTZ,
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
	isAdminUser BOOLEAN NOT NULL DEFAULT FALSE,
	isMfaRequired BOOLEAN DEFAULT FALSE,
	isMfaEnabled BOOLEAN DEFAULT FALSE,
	mfaSecret VARCHAR(100),	
	updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
);

COMMENT ON TABLE base.zzz IS 'User authentication (see base.useracc for authorisation)';
COMMENT ON COLUMN base.zzz.xxx IS 'userName';
COMMENT ON COLUMN base.zzz.yyy IS 'User password';
COMMENT ON COLUMN base.zzz.attempts IS 'Current number of consecutive login fails';
COMMENT ON COLUMN base.zzz.attemptsLockOut IS 'The start timestamp of a login lockout';
COMMENT ON COLUMN base.zzz.isEmailVerified IS 'User''s email address has been verified';
COMMENT ON COLUMN base.zzz.orgNrDefault IS 'Default org, used for determining the user''s org settings, eg password reset';
COMMENT ON COLUMN base.zzz.isMfaRequired IS 'Depends on the org, if org = optional then mfa is used if true';

CREATE TABLE base.userAcc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    zzzid BIGINT NOT NULL,
    orgNr INTEGER NOT NULL,
	encoded TEXT,
    lastLogin TIMESTAMPTZ,
    classification INTEGER DEFAULT 0,
    isAdminLang BOOLEAN NOT NULL DEFAULT FALSE,
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
	updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    FOREIGN KEY (zzzid) REFERENCES base.zzz(id),
    FOREIGN KEY (orgNr) REFERENCES base.org(nr)
);
COMMENT ON TABLE base.userAcc IS 'User authorisation for a specific orgNr';
COMMENT ON COLUMN base.userAcc.isAdminLang IS 'User can administer languages';

CREATE TABLE base.role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    orgNr INTEGER NOT NULL,
    code VARCHAR(100) NOT NULL,
    descr TEXT,
    encoded TEXT,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    UNIQUE (orgNr, code),
    FOREIGN KEY (orgNr) REFERENCES base.org(nr)
);

CREATE TABLE base.rolePermission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    roleId BIGINT NOT NULL,
    permissionNr INTEGER NOT NULL,
    crud VARCHAR(10) NOT NULL,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    UNIQUE (roleId, permissionNr),
    FOREIGN KEY (roleId) REFERENCES base.role(id)
);

CREATE TABLE base.userAccRole (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    userAccId BIGINT NOT NULL,
    roleId BIGINT NOT NULL,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	fromDate DATE,
	toDate DATE,
	version INTEGER NOT NULL DEFAULT 1,
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    UNIQUE (userAccId, roleId),
    FOREIGN KEY (userAccId) REFERENCES base.useracc(id),
    FOREIGN KEY (roleId) REFERENCES base.role(id)
);
COMMENT ON TABLE base.userAccRole IS 'Junction between roles and user accounts';
COMMENT ON COLUMN base.userAccRole.fromDate IS 'Role Effective from date (inclusive)';
COMMENT ON COLUMN base.userAccRole.toDate IS 'Role Effective to date (inclusive)';


CREATE TABLE base.langCode (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(4) NOT NULL,
    descr TEXT NOT NULL,
	flag TEXT,
    encoded TEXT,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    isActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE base.langKey (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack TEXT,
    code VARCHAR(100) NOT NULL UNIQUE,
    descr TEXT,
    encoded TEXT,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE base.langLabel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    langKeyId BIGINT NOT NULL,
    langCode VARCHAR(4) NOT NULL,
    variant INTEGER,
    code TEXT NOT NULL,
    tooltip TEXT,
    encoded TEXT,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 1,
    UNIQUE (langKeyId, langCode, variant),
    FOREIGN KEY (langKeyId) REFERENCES base.langKey(id)
);
CREATE INDEX idx_langLabel_unaccent ON base.langLabel (immutable_unaccent(lower(code)));


CREATE TABLE base.audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orgNr INTEGER NOT NULL,
    source INTEGER NOT NULL,
    entityTypeNr INTEGER NOT NULL,
    entityId BIGINT,
    userAccId BIGINT NOT NULL,
	masqueradeId BIGINT,
    created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	crud VARCHAR(10),
    details TEXT
);

COMMENT ON TABLE base.audit IS 'Log of all CRUD transations ';
COMMENT ON COLUMN base.audit.source IS 'Client source, eg web, mobile, api';
COMMENT ON COLUMN base.audit.entityTypeNr IS 'The entity defined in GC EntityTypes, eg Role, Org';
COMMENT ON COLUMN base.audit.entityId IS 'The primary key for the entity in question';
COMMENT ON COLUMN base.audit.userAccId IS 'User account Id';
COMMENT ON COLUMN base.audit.masqueradeId IS 'User account Id that is using masquerade';
COMMENT ON COLUMN base.audit.created IS 'Date time the audit record was created';
COMMENT ON COLUMN base.audit.version IS 'Record version number at the time the audit record was created';
COMMENT ON COLUMN base.audit.crud IS 'CRUD action';

--Delete me?
CREATE TABLE base.template (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nr INTEGER NOT NULL,
	orgNr INTEGER NOT NULL,
    code TEXT NOT NULL,
    langCode VARCHAR(4) NOT NULL,
	UNIQUE (nr, orgNr, langCode)
);